# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mothers_day', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='Message',
        ),
    ]
