# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mothers_day', '0002_auto_20180510_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='text',
        ),
        migrations.RemoveField(
            model_name='message',
            name='title',
        ),
    ]
